### ISSUE TITLE
Support react native 0.59+

### ISSUE THREAD

**Issue by gomdolkim** [jigaryadav/react-native-check-notification-enable#2]
I'd like to contribute one PR to support react native 0.59+. can you give me the permission to create PR?

**Comment by gomdolkim** [comment]
@jigaryadav

**Comment by jigaryadav** [comment]
> I'd like to contribute one PR to support react native 0.59+. can you give me the permission to create PR?

sure, create a pull request i will merge the commit @gomdolkim

**Comment by jigaryadav** [comment]
RN 59 and 60 is supported now @gomdolkim

**Comment by gomdolkim** [comment]
Thank you for your support.
